language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  # http://conda.pydata.org/docs/travis.html
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

cache:
  directories:
    - $HOME/.cache/pip

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy astropy
  - source activate test-environment
  - pip install pyastronomy
  - python setup.py install

  - pip install pytest-cov python-coveralls codeclimate-test-reporter codacy-coverage
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest --cov=spectrum_overload --cov-report term-missing --durations 10
  - coverage xml

after_success:
  - coveralls
  - codeclimate-test-reporter
  - python-codacy-coverage -r coverage.xml
